-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 11:45:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zsp_movie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zsp_movie` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zsp_movie` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `zsp_movie` ;

-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `is_admin` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `directed_by` VARCHAR(45) NULL,
  `lenght` INT NULL,
  `year` VARCHAR(45) NULL,
  `admin_id` INT NOT NULL,
  `accounts_id` INT NOT NULL,
  PRIMARY KEY (`id`, `admin_id`, `accounts_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `movies_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movies_has_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `movies_has_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movies_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`, `movies_id`, `categories_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rents` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  `accounts_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `accounts_id`, `movies_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
